# Generated by Django 2.1.1 on 2018-09-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawntransaction',
            name='current_month_days',
            field=models.IntegerField(default=31),
        ),
    ]
