# Generated by Django 2.1.1 on 2018-09-30 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_auto_20180930_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pawntransaction',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
